{% set name = "conjure-python-client" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6128bcd2dc7785d9f49c66e2d5122cb508fc70274210a63c33f903bb70a91870

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - enum34  # [py<34]
    - requests
    - typing

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python client and JSON encoders for use with generated Conjure clients'

extra:
  recipe-maintainers:
    - ferozco
    - iamdanfox
    - ahigginspalantir
